In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a=np.array([1,2,3,4,5,6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a[0]

np.int64(1)

In [8]:
a[0]=10

In [9]:
a

array([10,  2,  3,  4,  5,  6])

In [10]:
a[:3]

array([10,  2,  3])

In [11]:
a[3:]

array([4, 5, 6])

In [12]:
a[2:4]

array([3, 4])

In [13]:
a

array([10,  2,  3,  4,  5,  6])

In [14]:
b=a[3:]

In [15]:
b

array([4, 5, 6])

In [16]:
b[0]=40

In [17]:
a

array([10,  2,  3, 40,  5,  6])

In [18]:
b

array([40,  5,  6])

That changes the first element of b, which is also a[3]. So a is updated too.

In short
a[3:] creates a view on a
b[0] refers to the same memory as a[3]
assigning b[0] = 40 changes a[3]
therefore a now contains 40 in that position
If you want b to be independent, use b = a[3:].copy().

# copy example

In [19]:
a

array([10,  2,  3, 40,  5,  6])

In [20]:
x=a[3:].copy()

In [21]:
x

array([40,  5,  6])

In [22]:
x[1]=50

In [23]:
x

array([40, 50,  6])

In [24]:
a

array([10,  2,  3, 40,  5,  6])

In [25]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [26]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a.shape

(3, 4)

In [28]:
a[1,3]

np.int64(8)

In [29]:
a.ndim

2

In [30]:
a.shape

(3, 4)

In [31]:
a.size

12

# create basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()



In [32]:
np.zeros(2)

array([0., 0.])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.empty(4)

array([0.00000000e+000, 8.30712831e-312, 8.30712831e-312, 8.30712832e-312])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(5,12,2)

array([ 5,  7,  9, 11])

In [37]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
x=np.ones(2,dtype=np.int64)

In [39]:
x

array([1, 1])

# Adding, removing, and sorting elements

In [40]:
arr=np.array([2,1,5,3,7,4,6,8])

In [41]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [42]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [44]:
np.lexsort(arr)

np.int64(0)

In [45]:
np.searchsorted(arr,5)

np.int64(2)

In [46]:
np.searchsorted(arr,500)

np.int64(8)

In [47]:
np.partition(arr,3)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.concatenate((a, b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
a=np.array([5,6,7,8])
b=np.array([1,2,3,4])
c=np.concatenate((a, b))

In [ ]:
c

array([5, 6, 7, 8, 1, 2, 3, 4])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array.

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

### Can you reshape an array?
This section covers arr.reshape()

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b=a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

### How to convert a 1D array into a 2D array (how to add a new axis to an array)
This section covers np.newaxis, np.expand_dims

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
a.shape

(6,)

In [ ]:
a2=a[np.newaxis,:]

In [ ]:
a2.shape

(1, 6)