In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

You can explicitly convert a 1D array to either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension

In [3]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [4]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

Or, for a column vector, you can insert an axis along the second dimension:



In [6]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [7]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

For example, if you start with this array:

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [9]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [10]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [11]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and slicing

In [12]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [13]:
data[1]

np.int64(2)

In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [15]:
print(a[a < 5])

[1 2 3 4]


In [23]:
five_up= (a >= 5)

In [24]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [25]:
divisible_by_3 = (a % 3 == 0)

In [26]:
print(a[divisible_by_3])

[ 3  6  9 12]


In [27]:
c=a[(a>2) & (a<11)]

In [28]:
print(c)

[ 3  4  5  6  7  8  9 10]


In [29]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [31]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [33]:
list__of_coordinates=list(zip(b[0], b[1]))
for coordinate in list__of_coordinates:
    print(coordinate)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [34]:
print(a[b])

[1 2 3 4]


In [35]:
not_there=np.zeros_like(a, dtype=bool)
not_there[a == 42] = True

In [36]:
print(not_there)

[[False False False False]
 [False False False False]
 [False False False False]]


## How to create an array from existing data

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

You can easily create a new array from a section of an existing array.

In [37]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr1=a[3:8]

In [39]:
arr1

array([4, 5, 6, 7, 8])

In [40]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [41]:
a1

array([[1, 1],
       [2, 2]])

In [42]:
a2

array([[3, 3],
       [4, 4]])

In [43]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [44]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [45]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [47]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [49]:
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
b2=a.copy()

### Basic array operations

In [51]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [52]:
data - ones
data * data
data / data

array([1., 1.])

In [53]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [55]:
print(a.sum())

10


In [57]:
b = np.array([[1, 1], [2, 2]])

In [58]:
b.sum(axis=0)

array([3, 3])

In [59]:
b.sum(axis=1)

array([2, 4])

## Broadcasting